services:
  lnk:
    build: .
    ports:
      - "80:80"
    volumes:
      - lnk_data:/data
    environment:
      - PORT=80
      - DATA_DIR=/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80/",
        ]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

volumes:
  lnk_data:
    driver: local
